[package]
name = "minesweeper"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2.15", features = ["js"] }